apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: kustomize
    kaniko:
      dockerfile: dockerfile
      buildArgs:
        IMAGE_REPO: "{{.IMAGE_REPO}}"
        IMAGE_NAME: "{{.IMAGE_NAME}}"
        IMAGE_TAG: "{{.IMAGE_TAG}}"
        VERSION: "{{.IMAGE_TAG}}"
        HTTP_PROXY: "{{.HTTP_PROXY}}"
        http_proxy: "{{.HTTP_PROXY}}"
        HTTPS_PROXY: "{{.HTTPS_PROXY}}"
        https_proxy: "{{.HTTPS_PROXY}}"
        NO_PROXY: "{{.NO_PROXY}}"
        no_proxy: "{{.NO_PROXY}}"
      env:
      - name: HTTP_PROXY
        value: "{{.HTTP_PROXY}}"
      - name: HTTPS_PROXY
        value: "{{.HTTPS_PROXY}}"
      - name: NO_PROXY
        value: "{{.NO_PROXY}}"
      cache:
        repo: _cache
      image: gcr.io/kaniko-project/executor
      initImage: busybox:latest
  cluster:
    namespace: cocdit-build
    dockerConfig:
      path: "~/.docker/config.json"
    serviceAccount: kaniko
    runAsUser: 0
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 8
        memory: 16Gi
profiles:
### DEVELOPMENT ENVIRONMENTS (DEBUG)
- name: debug
  patches:
    - op: replace
      path: /build/artifacts/0/image
      value: docker.rsint.net/rs_ruscloud-dit-public/kustomize
    - op: replace
      path: /build/artifacts/0/kaniko/dockerfile
      value: debug.dockerfile
### SOFTWARE STAGES (DEV/QUAL/PROD)
### REGIONS - REGION SPECIFIC CONFIG PROFILES
- name: onprem
  activation:
  - kubeContext: ".*-0eu1-.*"
  patches:
    - op: replace
      path: /build/artifacts/0/image
      value: docker.rsint.net/rs_ruscloud-dit-public/kustomize
    - op: replace
      path: /build/artifacts/0/kaniko/cache/repo
      value: docker.rsint.net/rs_ruscloud-dit-public/_cache
    - op: replace
      path: /build/artifacts/0/kaniko/image
      value: docker.rsint.net/rs_ruscloud-dit-public/gcr.io/kaniko-project/executor:debug
    - op: replace
      path: /build/artifacts/0/kaniko/initImage
      value: docker.rsint.net/rs_ruscloud-dit-public/busybox:latest
    - op: replace
      path: /build/cluster/namespace
      value: cocdit-build
### CLUSTERS - INFRASTRUCTURE SPECIFIC CONFIG PROFILES
# <empty>
## LEGACY CLUSTERS
# chmu27 - okd-3.11 - first ever build cluster
- name: chmu27
  activation:
  - kubeContext: ".*-chmu27-.*"
  patches:
    - op: replace
      path: /build/artifacts/0/image
      value: registry-d.rsint.net/coc-dit/kustomize